### ISSUE TITLE
Use fetch instead of Axios

### ISSUE THREAD

**Issue by Mogztter** [neo4j-contrib/training-v2#15]
`fetch` is already available in modern browsers and if we want to support older browser we can use this polyfill: https://www.npmjs.com/package/whatwg-fetch (46.5 kB vs 346 kB for Axios).
The idea is to avoid adding an extra dependency when the browser platform provides a similar feature.

Arguably, we could also just stick with `jQuery.ajax()` since JQuery is already available on WordPress.

Here's a quick comparison:

**Fetch**
```js
const [err, response] = await to(fetch(constants.getApiBaseUrl(stage) + `/getClassEnrollment?className=${trainingClassName}`,
  {
    headers: {
      'Content-Type': 'application/json',
      'Authorization': accessToken
    }
  })
  .then((response) => response.json()))
return [err, response]
```

**Axios**
```js
const [err, response] = await to(Axios.get(constants.getApiBaseUrl(stage) + `/getClassEnrollment?className=${trainingClassName}`,
{
  headers: {
      'Content-Type': 'application/json',
      'Authorization': accessToken
  }
}))
return [err, response];
```

If we want to check the status of the response from `fetch` we can use the following code:

```js
_checkStatus(response) {
  if (response.status >= 200 && response.status < 300) {
    return response
  } else {
    const error = new Error(response.statusText)
    error.response = response
    throw error
  }
}
```

**Comment by spgandhi** [comment]
Makes sense. Let's go ahead with using `fetch` then

**Comment by Mogztter** [comment]
Ok I will submit a pull request then :+1:
